name: Update Blog Posts

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:

jobs:
  update-blogs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Fetch Medium posts
      - name: Fetch Medium posts
        id: medium
        uses: jeffreytse/medium-rss-to-json-action@v1.1.0
        with:
          feed_url: https://medium.com/feed/@zobayermahmud00

      # Fetch Dev.to posts
      - name: Fetch Dev.to posts
        id: devto
        uses: dawidd6/action-get-remote-json@v2
        with:
          url: https://dev.to/api/articles?username=zobayermahmud

      # Update README.md
      - name: Update README with latest blogs
        run: |
          {
            echo "<!-- BLOG-POST-LIST:START -->"

            # Medium posts
            echo '${{ steps.medium.outputs.json }}' | jq -r '.items[] | "- [" + .title + "](" + .link + ") (Medium)"' | head -n 5

            # Dev.to posts
            echo '${{ steps.devto.outputs.json }}' | jq -r '.[] | "- [" + .title + "](" + .url + ") (Dev.to)"' | head -n 5

            echo "<!-- BLOG-POST-LIST:END -->"
          } > blog_section.md

          awk 'BEGIN{found=0} /<!-- BLOG-POST-LIST:START -->/{found=1; system("cat blog_section.md"); next} /<!-- BLOG-POST-LIST:END -->/{found=0; next} !found {print}' README.md > README.tmp

          mv README.tmp README.md

      # Commit & push changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "🔄 Update latest blog posts" || echo "No changes to commit"
          git push
